language: objective-c
node_js:
  - "0.10"
install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install -g cordova
  - npm install -g purplecabbage/cordova-paramedic
  - npm install -g ios-sim
  - cordova create app-preferences-app
  - cd app-preferences-app
  - cordova platform add ios android
  - cordova plugin add https://github.com/apla/me.apla.cordova.app-preferences
  - cordova prepare
script:
  - cordova-paramedic --platform ios --plugin plugins/me.apla.cordova.app-preferences
