# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
#  NODE_PATH: %CD%\node_modules;%NODE_PATH%
#  my_var2: value2

cache:
  - node_modules                    # local npm modules
  - %APPDATA%\npm-cache             # npm cache

# getting cordova tools dependencies from github
# to make sure we're using their latest versions
install:
  - SET PATH=%CD%\node_modules\.bin;%PATH%
  - SET NODE_PATH=%CD%\node_modules;%NODE_PATH%
  - npm install
  - cordova create app-preferences-app

build: off

test_script:
  # testing basic functionality of preference generator
  - echo running jasmine test
  - cd bin
  - jasmine
  - cd ..
  # let's create cordova app, add and remove plugin a few times
  - echo test plugin within cordova app
  - cd app-preferences-app
  - cordova platform add windows
  - cordova plugin add https://github.com/apla/me.apla.cordova.app-preferences
